replicaCount: 1

image:
  repository: quay.io/number9/core-dump-handler:v2.0.10 
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

daemonset:
    name: "core-dump-handler"
    label: "core-dump-ds"
    hostDirectory: "/core-dump-handler"
    s3AccessKey : XXX
    s3Secret : XXX
    s3BucketName : XXX
    s3Region : XXX
    vendor: default
         
serviceAccount:
  create: true
  name: "core-dump-admin"

clusterRole:
  name: "core-dump-event-reporter"

clusterRoleBinding:
  name: "core-dump-event-report"
