# permissions for end users to view coredumphandlers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coredumphandler-viewer-role
rules:
- apiGroups:
  - charts.ibm.com
  resources:
  - coredumphandlers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.ibm.com
  resources:
  - coredumphandlers/status
  verbs:
  - get
