# permissions for end users to edit coredumphandlers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coredumphandler-editor-role
rules:
- apiGroups:
  - charts.ibm.com
  resources:
  - coredumphandlers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.ibm.com
  resources:
  - coredumphandlers/status
  verbs:
  - get
