apiVersion: v1
kind: ServiceAccount
metadata:
  name: uploader-sa
  namespace: system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: uploader-role
subjects:
  - kind: ServiceAccount
    name: uploader-sa
    namespace: system
roleRef:
  kind: ClusterRole
  name: uploader-rbac
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: uploader-rbac
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]