apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: core-dump-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: An operator to manage core dumps
  displayName: Core Dump Handler
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - core dump
  - post mortem
  - observability
  links:
  - name: Core Dump Operator
    url: https://core-dump-operator.domain
  maintainers:
  - email: anton@venshare.com
    name: anton whalley
  maturity: alpha
  provider:
    name: Anton Whalley
    url: https://github.com/IBM/core-dump-handler
  version: 0.0.0
