apiVersion: v1
kind: Secret
metadata:
  name: core-dump-handler-user-cred
type: core-dump-handler # required. core-dump-handler looks up users' secrets with this key.
stringData:
  bucket: "mybucket"
  keyPrefix: "core-dump-handler-test/"
  accessKey: "ABCDEFG"
  secretKey: "1234567890"
  endpoint: "https://myendpoint"
  createBucket: "false"
